{
 "title": "OZON Business Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Unique Offers Viewed By Device Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    DeviceTypeName,\n    COUNT(DISTINCT ContentUnitID) as unique_offers_viewed\nFROM raw_events\nGROUP BY DeviceTypeName\nORDER BY unique_offers_viewed DESC;"
    }
   ]
  },
  {
   "title": "Event Count By Device Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    DeviceTypeName,\n    COUNT() as event_count\nFROM raw_events\nGROUP BY DeviceTypeName\nORDER BY event_count DESC;"
    }
   ]
  },
  {
   "title": "Top 30 Vendors",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    vendor,\n    offers_count\nFROM catalog_by_vendor_mv\nORDER BY offers_count DESC\nLIMIT 30;"
    }
   ]
  },
  {
   "title": "Top 20 Categories",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    toString(category_id) as category_id,\n    offers_count\nFROM catalog_by_category_mv\nORDER BY offers_count DESC\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Event Coverage By Category",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n    o.category_id,\n    COUNT(DISTINCT o.offer_id) as total_offers,\n    COUNT(DISTINCT e.ContentUnitID) as covered_offers,\n    ROUND((covered_offers / total_offers) * 100, 2) as coverage_percent\nFROM ecom_offers o\nLEFT JOIN raw_events e ON o.offer_id = e.ContentUnitID\nGROUP BY o.category_id\nORDER BY coverage_percent ASC;"
    }
   ]
  }
 ]
}